name: Executar script Python semanalmente

on:
  schedule:
    - cron: '0 10 * * 0'  # Toda segunda-feira às 10:00 UTC
  workflow_dispatch:       # Permite executar manualmente

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Executar script
        run: main.py
